### ISSUE TITLE
Flatpak(Appimage) edition failed to launch on KDE neon(based on Ubuntu 16.04)

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [ozmartian/vidcutter#105]
Traceback:

```
./VidCutter-5.0.0-x64.AppImage                                
/bin/bash: /tmp/.mount_VidCutPWACDo/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)                                  
Failed to import the site module
Traceback (most recent call last):
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/site.py", line 587, in <module>
    main()
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/site.py", line 573, in main
    known_paths = addusersitepackages(known_paths)
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/_sysconfigdata.py", line 1, in <module>
    import importlib
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/importlib/__init__.py", line 57, in <module>
    import types
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/tmp/.mount_VidCutPWACDo/usr/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'
```

**Comment by moocan** [comment]
Hello,

Exactly the same error under gnome, mate or cinnamon on ubuntu 16.04 LTS

`/opt/VidCutter-5.0.0/VidCutter-5.0.0-x64.AppImage 
/bin/bash: /tmp/.mount_VidCutI30r5B/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
Failed to import the site module
Traceback (most recent call last):
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 587, in <module>
    main()
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 573, in main
    known_paths = addusersitepackages(known_paths)
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var
    return get_config_vars().get(name)
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/_sysconfigdata.py", line 1, in <module>
    import importlib
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/importlib/__init__.py", line 57, in <module>
    import types
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'`

Kr
Moo

**Comment by ozmartian** [comment]
Hi @moocan,



Current AppImage is moreso aimed for those still stuck on Trusty/Vivid distro. AppImage is currently tested and built on Trusty but uses and older AppImage runtime and build spec which I'll look into updating soon. Flatpak and Snap packages can also be worked on if there are requests for it.



Out of curiosity, why not use the Launchpad PPA which will work perfectly for you on KDE Neon or are you trying AppImage to check the app out minus having to install? Just curious re user needs and wants is all!



Should hopefully have a newer AppImage ready in the next day or two when time allows, and will ensure its working on Neon.



Cheers,
Pete




---- On Wed, 22 Nov 2017 08:09:55 +0800 moocan &lt;notifications@github.com&gt; wrote ----




Hello,

Exactly the same error under gnome, mate or cinnamon on ubuntu 16.04 LTS

/opt/VidCutter-5.0.0/VidCutter-5.0.0-x64.AppImage /bin/bash: /tmp/.mount_VidCutI30r5B/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash) Failed to import the site module Traceback (most recent call last): File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 587, in &lt;module&gt; main() File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 573, in main known_paths = addusersitepackages(known_paths) File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 287, in addusersitepackages user_site = getusersitepackages() File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 263, in getusersitepackages user_base = getuserbase() # this will also set USER_BASE File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/site.py", line 253, in getuserbase USER_BASE = get_config_var('userbase') File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/sysconfig.py", line 595, in get_config_var return get_config_vars().get(name) File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/sysconfig.py", line 538, in get_config_vars _init_posix(_CONFIG_VARS) File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/sysconfig.py", line 410, in _init_posix from _sysconfigdata import build_time_vars File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/_sysconfigdata.py", line 1, in &lt;module&gt; import importlib File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/importlib/__init__.py", line 57, in &lt;module&gt; import types File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/types.py", line 166, in &lt;module&gt; import functools as _functools File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/functools.py", line 23, in &lt;module&gt; from weakref import WeakKeyDictionary File "/tmp/.mount_VidCutI30r5B/usr/lib/python3.5/weakref.py", line 12, in &lt;module&gt; from _weakref import ( ImportError: cannot import name '_remove_dead_weakref'

Kr

 Moo

**Comment by ozmartian** [comment]
Launchpad PPA now ONLY works for Ubuntu 20 and above.
