### ISSUE TITLE
App doesn't start in Arch Linux

### ISSUE THREAD

**Issue by btd1337** [ozmartian/vidcutter#127]
This error ocurrs when trying to open.

```
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 11, in <module>
    load_entry_point('vidcutter==5.0.5', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/vidcutter/__main__.py", line 41, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3.6/site-packages/vidcutter/videocutter.py", line 42, in <module>
    from vidcutter.about import About
  File "/usr/lib/python3.6/site-packages/vidcutter/about.py", line 37, in <module>
    import vidcutter.libs.mpv as mpv
ImportError: libcdio.so.18: cannot open shared object file: No such file or directory

```

**Comment by kuboosoft** [comment]
https://github.com/ozmartian/vidcutter/issues/115#issuecomment-353990875

**Comment by ozmartian** [comment]
@btd1337 thats strange since all the necessary dependencies are specified in the PKGBUILD script. I've spent sometime investigating and I honestly cannot figure out why you're having this issue although its very simple to resolve. for some strange reason a package used/needed by VidCutter on your system is also requiring libcdio so you simply need to install it which should stop that error from  occurring but it doesn't explain why you're having this issue to start with, unless you have a broken package setup via having installed things in the past by force etc.

anyways,  to fix things and hopefully get VidCutter launching on your system run this in a terminal:

`$ sudo pacman -S libcdio`

I don't have that library installed on any of my Arch installations here and have never seen it being used by any of VidCutter's dependencies which is a small list. According to ArchLinux's package info at https://www.archlinux.org/packages/extra/x86_64/libcdio this library is required by the following:

- clementine
- gst-plugins-ugly
- kodi
- lib32-libcdio
- libcdio-paranoia
- pcsxr
- python2-pycdio
- python-pycdio
- tellico
- vcdimager
- deadbeef (optional)
- vlc (optional)
- deadbeef (make)
- kodi (make)
- python2-pycdio (make)

and none of those are used or needed by VidCutter either during initial build our standard running phases. Let me know if you're able to figure it out or just ignore it if things are working fine once libcdio is installed to save yourself from going insane :)

Cheers,
Pete

**Comment by ozmartian** [comment]
@btd1337 forgot to ask what flavour of Arch you happen to be running on i.e. standard vanilla ArchLinux or something like Manjaro or Antergos

Cheers,
Pete

**Comment by btd1337** [comment]
I'm using the Arch Linux Standard.

**Comment by Freso** [comment]
Arch package `libcdio` provides `libcdio.so.19`, not `libcdio.so.18`. I’m having the same issue with another (unrelated) Python package.

**Comment by ozmartian** [comment]
@Freso i cannot replicate this with Arch... v6.0.0 is available via AUR so ensure you're using that... i've even setup a new Arch installation to then install from AUR and no issues... 

keep me posted,
thx!

**Comment by Freso** [comment]
@ozmartian Oh, I don’t even use vidcutter—I found this issue by searching for the error string. The issue only happens due to compiling (locally) against older `.so` files. Like I said, I had another Python module that had a C part compiled against `libcdio.so.18` but libcdio had since then been updated so now `libcdio.so.19` was on my system, with no `.18`. The solution is (obviously?) to recompile any C parts of the Python libraries complaining about this so that they’re now compiled against the newer `.so` library.
