### ISSUE TITLE
Exception: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by evds** [ozmartian/vidcutter#140]
version: vidcutter 5.5.0

2018-02-07 22:09 - vidcutter.libs.videoservice - ERROR - Exception during MPEG-TS join
Traceback (most recent call last):
  File "vidcutter\libs\videoservice.py", line 548, in mpegtsJoin
  File "vidcutter\libs\videoservice.py", line 462, in getBSF
  File "vidcutter\libs\videoservice.py", line 266, in codecs
AttributeError: 'NoneType' object has no attribute 'group'
2018-02-07 22:09 - vidcutter.libs.videoservice - INFO - smartcut MPEG-TS join failed, retry with standard concat
2018-02-07 22:09 - vidcutter.libs.videoservice - INFO - C:\************\bin\ffmpeg.exe -hide_banner -v error -f concat -segment_time_metadata 1 -safe 0 -i "C:\test\_vidcutter.list" -c copy -map 0 -y "C:\test\test_EDIT_00.mp4"
2018-02-07 22:10 - vidcutter.libs.mpvwidget - INFO - [vd] Uninit video.
2018-02-07 22:10 - vidcutter.libs.mpvwidget - INFO - [lavf] deselect track 0
2018-02-07 22:10 - vidcutter.libs.mpvwidget - INFO - [cplayer] Video: no video
2018-02-07 22:10 - vidcutter.libs.mpvwidget - INFO - [cplayer] EOF code: 6

**Comment by Dyras** [comment]
Yup same here on W10

https://github.com/ozmartian/vidcutter/issues/138#issuecomment-363897433

**Comment by eharris** [comment]
This problem seems to still be present, using vidcutter packaged deb 6.0.0-1 amd64 under Debian stretch with all updates.  

After this occurs, the resulting saved video file is unplayable, with VLC just showing the first frame and spewing lots of errors to the console.

Updated debug log snippet below:

```
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - /usr/bin/ffprobe -hide_banner -v error -show_packets -select_streams v -show_entries packet=pts_time,flags -of csv "/raid/transfer/cleaning/new/test.mp4"
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - -v 32 -i "/raid/transfer/cleaning/new/test.mp4" -ss 144.811 -t 0.0003329999999834854 -c:v libx264 -tune film -preset ultrafast -x264-params crf=23 -qp 0 -flags +cgop -c:a copy -c:s copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/tmp/vidcutter/test_EDIT_00_start_00.mp4"
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - -v error -ss 146.6465 -t 27.827799999999996 -i "/raid/transfer/cleaning/new/test.mp4" -c copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/tmp/vidcutter/test_EDIT_00_middle_00.mp4"
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - -v 32 -i "/raid/transfer/cleaning/new/test.mp4" -ss 174.4743 -t 0.9007000000000005 -c:v libx264 -tune film -preset ultrafast -x264-params crf=23 -qp 0 -flags +cgop -c:a copy -c:s copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -y "/tmp/vidcutter/test_EDIT_00_end_00.mp4"
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'middle': False, 'start': True, 'end': False}
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'middle': True, 'start': True, 'end': False}
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'middle': True, 'start': True, 'end': True}
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - /usr/bin/ffmpeg -hide_banner -i "/tmp/vidcutter/test_EDIT_00_middle_00.mp4"
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - smartcut files are MPEG based so join via MPEG-TS
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - /usr/bin/ffmpeg -hide_banner -i "/tmp/vidcutter/test_EDIT_00_start_00.mp4"
2019-07-10 11:03 - vidcutter.libs.videoservice - ERROR - Exception during MPEG-TS join
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 619, in mpegtsJoin
    video_bsf, audio_bsf = self.getBSF(inputs[0])
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 491, in getBSF
    vcodec, acodec = self.codecs(source)
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 268, in codecs
    acodec = re.search(r'Stream.*Audio:\s(\w+)', result).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - smartcut MPEG-TS join failed, retry with standard concat
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - /usr/bin/ffmpeg -hide_banner -v error -f concat -safe 0 -i "/tmp/vidcutter/_vidcutter.list" -c copy -map 0 -y "/tmp/vidcutter/test_EDIT_00.mp4"
2019-07-10 11:03 - vidcutter.libs.videoservice - INFO - /usr/bin/ffmpeg -hide_banner -v error -i "/raid/transfer/cleaning/new/test_EDIT.mp4" -map 0 -c copy -y "/raid/transfer/cleaning/new/test_EDIT_FINAL.mp4"
```
