### ISSUE TITLE
Can't install via PyPi

### ISSUE THREAD

**Issue by Rockus2018** [ozmartian/vidcutter#152]
hello,

despite I installed vidcutter through the PPA repository, as appimage and from source in the meanwhile:

------------------------------------------------------------------------

rockus@Lychee ~ $ pip3 install -U vidcutter
Collecting vidcutter
  Downloading vidcutter-5.5.0.tar.gz (2.3MB)
    100% |████████████████████████████████| 2.3MB 522kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2wc_bj93/vidcutter/setup.py", line 39, in <module>
        from helpers import SetupHelpers
    ModuleNotFoundError: No module named 'helpers'
    
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2wc_bj93/vidcutter/

rockus@Lychee ~ $ pip3 install -U setuphelpers
Requirement already up-to-date: setuphelpers in /usr/local/lib/python3.6/site-packages

rockus@Lychee ~ $ python3 --version
Python 3.6.4

--------------------------------------------------------------

OS is Linux Mint 18.3 Cinnamon 64bit

Thanks in advance

**Comment by Flashwalker** [comment]
Same error on Ubuntu 20.04.  
```
sudo pip3 install vidcutter
Collecting vidcutter
  Using cached vidcutter-6.0.0.1.tar.gz (3.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k6jlyf_a/vidcutter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k6jlyf_a/vidcutter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-k6jlyf_a/vidcutter/pip-egg-info
         cwd: /tmp/pip-install-k6jlyf_a/vidcutter/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k6jlyf_a/vidcutter/setup.py", line 40, in <module>
        from helpers import SetupHelpers
    ModuleNotFoundError: No module named 'helpers'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```  
`pip3 install -U setuptools` doesn't solves.
