### ISSUE TITLE
ModuleNotFoundError: No module named 'helpers'

### ISSUE THREAD

**Issue by yurivict** [ozmartian/vidcutter#155]
Version 5.5.0 fails:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 39, in <module>
    from helpers import SetupHelpers
ModuleNotFoundError: No module named 'helpers'
```

'helpers' doesn't seem to be a python module.

**Comment by Rockus2018** [comment]
Sorry, I was first, isn't it ?

See #152 

[helpers.py](https://github.com/ozmartian/vidcutter/blob/master/helpers.py) is part of the vidcutter package.

**Comment by yurivict** [comment]
> helpers.py is part of the vidcutter package.

You added it later, after 5.5.0.
It needs to be in a release for people to see it.
