### ISSUE TITLE
Smartcut fails - "ERROR - Exception during MPEG-TS join"

### ISSUE THREAD

**Issue by gareth8118** [ozmartian/vidcutter#159]
Suspect this is the same issue as in #140 and #138 but my transcript is slightly different. Ubuntu 17.10 with all updates, installed vidcutter from the PPA.

```
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - /usr/bin/ffprobe -hide_banner -v error -show_packets -select_streams v -show_entries packet=pts_time,flags -of csv "/mnt/data/gareth/Resources/blender/blend_and_paint/videos/Blender-01_Ui.mp4"
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - -v error -ss 8.333333 -t 0.0 -i "/mnt/data/gareth/Resources/blender/blend_and_paint/videos/Blender-01_Ui.mp4" -c copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -copyinkf -y "/tmp/vidcutter/Blender-01_Ui_EDIT_00_middle_00.mp4"
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - -v 32 -i "/mnt/data/gareth/Resources/blender/blend_and_paint/videos/Blender-01_Ui.mp4" -ss 8.333333 -t 7.998667000000001 -c:v libx264 -tune film -preset ultrafast -x264-params crf=23 -qp 0 -flags +cgop -c:a copy -c:s copy -map 0:0 -map 0:1 -avoid_negative_ts 1 -copyinkf -y "/tmp/vidcutter/Blender-01_Ui_EDIT_00_end_00.mp4"
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'middle': True, 'end': False}
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - SmartCut progress: {'middle': True, 'end': True}
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - /usr/bin/ffmpeg -hide_banner -i "/tmp/vidcutter/Blender-01_Ui_EDIT_00_middle_00.mp4"
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - smartcut files are MPEG based so join via MPEG-TS
2018-04-01 19:07 - vidcutter.libs.videoservice - ERROR - Exception during MPEG-TS join
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 551, in mpegtsJoin
    name, _ = os.path.splitext(file)
  File "/usr/lib/python3.6/posixpath.py", line 120, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2018-04-01 19:07 - vidcutter.libs.videoservice - INFO - smartcut MPEG-TS join failed, retry with standard concat
2018-04-01 19:07 - root - CRITICAL -   File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 409, in smartcheck
    self.smartjoin(index)
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 437, in smartjoin
    allstreams=self.smartcut_jobs[index].allstreams)
  File "/usr/lib/python3/dist-packages/vidcutter/libs/videoservice.py", line 450, in join
    filelist = os.path.normpath(os.path.join(os.path.dirname(inputs[0]), '_vidcutter.list'))
  File "/usr/lib/python3.6/posixpath.py", line 154, in dirname
    p = os.fspath(p)

2018-04-01 19:07 - root - CRITICAL - <class 'TypeError'>: expected str, bytes or os.PathLike object, not NoneType
2018-04-01 19:07 - vidcutter.libs.mpvwidget - INFO - [vd] Uninit video.
2018-04-01 19:07 - vidcutter.libs.mpvwidget - INFO - [cplayer] Video: no video
2018-04-01 19:07 - vidcutter.libs.mpvwidget - INFO - [opengl-cb] flushing shader cache
2018-04-01 19:07 - vidcutter.libs.mpvwidget - INFO - [cplayer] Run command: quit, flags=0, args=[0]
```

**Comment by gareth8118** [comment]
Appears fixed in latest ppa build - closing.
