### ISSUE TITLE
Last vidcutter crashes

### ISSUE THREAD

**Issue by r3d9u11** [ozmartian/vidcutter#193]
Hi. vicutter crushes with:
```
$ vidcutter
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==6.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 36, in <module>
    from PyQt5.QtGui import (QCloseEvent, QContextMenuEvent, QDragEnterEvent, QDropEvent, QGuiApplication, QMouseEvent,
ImportError: cannot import name 'qt_set_sequence_auto_mnemonic'
```
Linux Mint 18.3 x64

**Comment by johnnieskywalker** [comment]
:( for me crashes  too :(
