### ISSUE TITLE
mpegtsJoin fails if clip starts at beginning of file

### ISSUE THREAD

**Issue by nullSoup** [ozmartian/vidcutter#214]
In 6.0.0 release of vidcutter, mpegtsJoin() in libs/videoservice.py currently assumes all clips are formed from start, middle, and end segments, but the smartcut function will omit the start or end segment if the clips starts on the first frame or ends on the last frame. As a result, vidcutter currently hangs when attempting to save and gives the following error:

> 2019-01-29 20:14 - vidcutter.libs.videoservice - INFO - smartcut files are MPEG based so join via MPEG-TS
> 2019-01-29 20:14 - vidcutter.libs.videoservice - ERROR - Exception during MPEG-TS join
> Traceback (most recent call last):
>   File "vidcutter\libs\videoservice.py", line 622, in mpegtsJoin
>   File "ntpath.py", line 224, in splitext
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> 2019-01-29 20:14 - vidcutter.libs.videoservice - INFO - smartcut MPEG-TS join failed, retry with standard concat
> 2019-01-29 20:14 - root - CRITICAL -   File "vidcutter\libs\videoservice.py", line 418, in smartcheck
>   File "vidcutter\libs\videoservice.py", line 446, in smartjoin
>   File "vidcutter\libs\videoservice.py", line 459, in join
>   File "ntpath.py", line 243, in dirname
>   File "ntpath.py", line 205, in split
> 
> 2019-01-29 20:14 - root - CRITICAL - <class 'TypeError'>: expected str, bytes or os.PathLike object, not NoneType

I believe the fix should be to add 'if file is not None' checks in mpegtsJoin() & cleanup() functions in libs/videoservice.py. Did a quick test with these two changes and it seems to correct the problem.

**Comment by nullSoup** [comment]
I see pull request #183 addresses this.
