### ISSUE TITLE
Problem running from source on Windows 10 (DLL load failed while importing mpv)

### ISSUE THREAD

**Issue by Zenahr** [ozmartian/vidcutter#336]
After installing dependencies blindly (since no requirements.txt file is provided as of now) I tried to run the following:

```py
python setup.py build_ext -i
python -m vidcutter
```

which resulted in this error:

```
(env) C:\SoftwareDevelopment\EasyCut>python setup.py build_ext -i
running build_ext
copying build\lib.win-amd64-3.8\vidcutter\libs\mpv.cp38-win_amd64.pyd -> vidcutter\libs

(env) C:\SoftwareDevelopment\EasyCut>python -m vidcutter
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\SoftwareDevelopment\EasyCut\vidcutter\__main__.py", line 41, in <module>
    from vidcutter.videocutter import VideoCutter
  File "C:\SoftwareDevelopment\EasyCut\vidcutter\videocutter.py", line 57, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "C:\SoftwareDevelopment\EasyCut\vidcutter\libs\mpvwidget.py", line 63, in <module>
    import vidcutter.libs.mpv as mpv
ImportError: DLL load failed while importing mpv: The specified module could not be found.
```

This is my environment:

```
Python 3.8.6

PyOpenGL==3.1.5
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
python-mpv==0.5.2
```

**Comment by Zenahr** [comment]
related to #308
