### ISSUE TITLE
How run code in ubuntu?

### ISSUE THREAD

**Issue by dacorsa** [ozmartian/vidcutter#352]
i have downloaded the latest code, installed all dependencies but have this error, 
NB: 14:54:41 root@NanoKDE /home/dacorsa # apt install python3-pyqt5
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
python3-pyqt5 è già alla versione più recente (5.15.6+dfsg-1ubuntu2).
0 aggiornati, 0 installati, 0 da rimuovere e 1 non aggiornati.
14:55:05 root@NanoKDE /home/dacorsa # 

14:52:59 dacorsa@NanoKDE /home/dacorsa $ cd /app/vidcutter/
14:53:06 dacorsa@NanoKDE /app/vidcutter master$ python3 setup.py build_ext -i
running build_ext
copying build/lib.linux-x86_64-3.10/vidcutter/libs/mpv.cpython-310-x86_64-linux-gnu.so -> vidcutter/libs
14:53:08 dacorsa@NanoKDE /app/vidcutter master$ python3 -m vidcutter
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/vidcutter/vidcutter/__main__.py", line 34, in <module>
    from PyQt5.QtCore import (pyqtSlot, QCommandLineOption, QCommandLineParser, QDir, QFileInfo, QProcess,
ModuleNotFoundError: No module named 'PyQt5.QtCore'
14:53:17 dacorsa@NanoKDE /app/vidcutter master$ 

How can i solve it?
Thanks

**Comment by dacorsa** [comment]
Hi guys, after an ubuntu update now dupeguru works!
thanks can close the ticket

**Comment by dacorsa** [comment]
bye
