### ISSUE TITLE
Flatpak version not working - PyQt5 not found

### ISSUE THREAD

**Issue by PlanetEater** [ozmartian/vidcutter#390]
```
$ flatpak run com.ozmartians.VidCutter
Traceback (most recent call last):
  File "/app/bin/vidcutter", line 5, in <module>
    from vidcutter.__main__ import main
  File "/app/lib/python3.10/site-packages/vidcutter/__main__.py", line 34, in <module>
    from PyQt5.QtCore import (pyqtSlot, QCommandLineOption, QCommandLineParser, QDir, QFileInfo, QProcess,
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

It looks like the included PyQt5 module is installed under /lib/python3.9 while everything else is under /lib/python3.10.

**Comment by ozmartian** [comment]
Fix applied for this issue. Thx for reporting it!

Will take at least 4hrs or so before it is published to the live repository.
