### ISSUE TITLE
snap install fails to run,  Debian  add-apt-repository also fails.

### ISSUE THREAD

**Issue by ManfredBartz** [ozmartian/vidcutter#398]
My system: 
```
NAME="Debian GNU/Linux"
VERSION="12 (bookworm)"
```

After **sudo snap install vidcutter**,
I try to run **vidcutter** from the commandline with these results:

```
mbz@t5810:~$ vidcutter
Gtk-Message: 10:25:42.503: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:25:42.503: Failed to load module "window-decorations-gtk-module"
^C
```

Did a **snap remove** and tried:

```
mbz@t5810:~$ sudo add-apt-repository ppa:ozmartian/apps
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
mbz@t5810:~$ 
```

**Comment by ozmartian** [comment]
Hi,



The PPA with Debian is out of date and no longer supported sorry. I will try rebuilding the Snap so it pull in newer dependencies, hopefully that should fix things. Try installing it tomorrow through Snap as it takes a good 4-6 hours for newly built Snaps to be available in the store.



Cheers,

Pete






---- On Mon, 08 Apr 2024 10:56:49 +1000 Manfred Bartz ***@***.***> wrote ---





My system:

NAME="Debian GNU/Linux"
VERSION="12 (bookworm)"


After sudo snap install vidcutter,
 I try to run vidcutter from the commandline with these results:
***@***.***:~$ vidcutter
Gtk-Message: 10:25:42.503: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:25:42.503: Failed to load module "window-decorations-gtk-module"
^C


Did a snap remove and tried:

***@***.***:~$ sudo add-apt-repository ppa:ozmartian/apps
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
***@***.***:~$

**Comment by benintech** [comment]
@ManfredBartz : for that specific `AttributeError`, the solution is to install `python3-launchpadlib`.

That being said, the installation of VidCutter will still fail (missing dependencies). I couldn't find a way to install it in Debian 12 (see https://github.com/ozmartian/vidcutter/issues/412).
