### ISSUE TITLE
Latest Vidcutter Not opening at all libmpv.so.1: undefined symbol 

### ISSUE THREAD

**Issue by defencedog** [ozmartian/vidcutter#42]
@ BunsenLabs x86, Debian

Installed latest version available n THIS date via adding ppa to Synaptic, everything installed fine
Invoking application from terminal throws this error & application won't run

```
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==3.2.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 38, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 55, in <module>
    import vidcutter.libs.mpv as mpv
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpv.py", line 333, in <module>
    _handle_func('mpv_create_client', [c_char_p], MpvHandle, notnull_errcheck)
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpv.py", line 286, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/i386-linux-gnu/libmpv.so.1: undefined symbol: mpv_create_client
```

All prerequisites are installed, although it seems my mpv version & libs are old, but should this be a problem?
http://imgur.com/P40k6UT

**Comment by ozmartian** [comment]
hey there,

yeh, its definitely due to your version of libmpv as its failing right at ctypes init which is the bridge between Python and the C based libmpv library... is must be a VERY old version though because "create_client" would have been in the library since inception, or so i assume anyway...

the only real solution here is getting your libs updated in a safe manner... Bunsenlabs is based on Debian Jessie which I have tested upon without issue...

were you running the previous version v3.0.0 of VidCutter or is this your first time checking it out? as previous version shouldn't work for you either...

i'm grabbing an ISO of Bunsenlabs to have a look and hopefully find a solution... you can simply just use the AppImage binary though... it should work as it targets older systems with all libs included.... if you can give that a try and i'll get back to you regarding proper installation once i've played around in Bunsen shortly...

**Comment by ozmartian** [comment]
@defencedog 

hello again.. i've checked it all out and the only way to get things working for a DEB package installation is by compiling mpv together with ffmpeg and all its dependant libs.. its so totally not worth the effort and may cause problems with other apps since ffmpeg is central to so much in Linux multimedia...

my suggestion is to stick with the AppImage... i tested it and it works just fine but just make sure mpv is installed via packages just to be sure codecs are all available but it should just work out of the box...

but now i recall you mentioned you were on x86?! the AppImage is only for x64, if i find the time I'll produce an x86 version for you.... or you could install the x86 Windows version using Wine :-) that actually works in Linux too, just not as pretty UI-wise but it works and is self contained

**Comment by defencedog** [comment]
Sir please do make Appimage for x86 :) ...Your application is the only application I UNINSTALLED windows completely. Bcz this was the application that completely substituted my Windows application named SolveigMM Video Splitter

Thanks in advance

**Comment by ozmartian** [comment]
hi again,

i played some more with a local installation of the latest32-bit Bunsenlabs release and found a much easier way to overcome the current issue with extremely outdated version of libmpv that ships with Debian stable. You could can switch your core packages to point to Debian testing (there is also experimental and "sid"). They all contain libmpv 0.23 and above. But only switching the one entry in your APT sources file, keeping updates and security etc. at jessie so its only core stuff that is affected.. I wouldn't worry about this with regards to it causing you issues elsewhere as Debian packagers are ultra conservative and careful. The testing repos are where packages live for a final round of user acceptance testing before being pushed out to stable. I switched, then upgraded and all was perfect.

Its a much better install re everything else too. By using Debian you get Qt 5.7 which is close to the very latest. You'll see improvements in many other places and you can always easily switch back to jessie stable shoud problems arise later down the track (which is extremely rare and unheard of anyways). So this is real easy, if you prefer not to do this then I should be able to produce a x86 AppImage for you instead, will just take a few days to complete.

There are many easy to follow guides only for "switching to Debian astesting from jessie". you just need to edit your APT sources file located at /etc/apt/sources.list as root user. Then modify the vry first uncommented line which should look like this by default:

    deb http://deb.debian.org/debian/ jessie main

and replace the "jessie' string to "stretch" so that it now looks like:

    deb http://deb.debian.org/debian/ stretch main

then save it and "sudo apt-get update" followed by "sudo apt-get dist-upgrade"

you can now install VidCutter via the PPA an all will work as it should. Also note, its best to use the Ubuntu Vivid package from the PPA ass that distro is closest to matching Debian Jessie.

Any issues or concerns just give us a shout. Let me know how you go so I can close this issue off :-)

Cheers!
