### ISSUE TITLE
 timeline slider doesn't drag.

### ISSUE THREAD

**Issue by davekimble2** [ozmartian/vidcutter#65]
Confirm Lubuntu 16.04, Vidcutter 3.5.0 - timeline slider doesn't drag.
I got a different effect when launched from terminal with filename and was able to complete the job OK.

**Comment by wrooot** [comment]
Try 4.0.0. It has fixed this issue for me (on Windows though).

**Comment by davekimble2** [comment]
ppa has updated to 4.0.0~201708021339~ubuntu16.04.1
```
$ vidcutter ./private/MyMovies/Kelly.mp4
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==4.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 39, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 48, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in <module>
    from OpenGL import GL
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'
$ 
```

**Comment by FredVoisin** [comment]
on Ubuntu 16.04 amd64, with vidcutter from ppa ozmartian,  same error "module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'" makes vidcutter unable to launch in any way.
