### ISSUE TITLE
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'

### ISSUE THREAD

**Issue by jeekajoo** [ozmartian/vidcutter#72]
Hi,

Last stable `4.0.0~201708021339~ubuntu16.04.1` fails to start on `Ubuntu 16.04.3 LTS`.
```
$ vidcutter
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==4.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 39, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 48, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in <module>
    from OpenGL import GL
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'
```
Thanks

**Comment by PandaJim** [comment]
Not know what's the problem, but I got a workaround by upgrade PyOpenGL via following command:

pip3 install --upgrade PyOpenGL

**Comment by PoulKalff** [comment]
I got it working same way as PandaJim. Shouldn't it be possible to have the program check pythonopengl-version, to better handle this error?

**Comment by manjarooo** [comment]
I think I have a similar problem:
I can not start vidcutter 4.0.0 (for Ubuntu 15.04) on **Linux Mint LMDE2 32bit**

PPA repos do not work in LMDE2, so I've downloaded the .deb package manually from here:
http://ppa.launchpad.net/ozmartian/apps/ubuntu/pool/main/v/vidcutter/
=> **vidcutter_4.0.0~201708100203~ubuntu15.04.1_i386.deb**

I couldn't install the Ubuntu 16.x or 17.x packages, because my python3 version is lower then v3.5.
These Python versions are installed:
```
$ python3 --version
Python 3.4.2
$ python --version
Python 2.7.9
```

When I install the vidcutter .deb, these packages are installed automatically:
python3-opengl (3.0.2-1)
freeglut3:i386 (2.8.1-2)
libmpv1:i386 (0.6.2-2)
libavdevice55:i386 (6:11.9-1~deb8u1)
libbs2b0 (3.1.0+dfsg-2.1)
libguess1:i386 (1.2-dmo2+deb8u1)
mediainfo (0.7.70-1)
libmediainfo0:i386 (0.7.70-1)
libmowgli-2-0:i386 (2.0.0-dmo1+deb8u1)
python3-pyqt5.qtopengl (5.3.2+dfsg-3)
python3-pyqt5 (5.3.2+dfsg-3)
libqt5help5:i386 (5.3.2-3)
libqt5clucene5:i386 (5.3.2-3)
libqt5designer5:i386 (5.3.2-3)
libqt5test5:i386 (5.3.2+dfsg-4+deb8u2)
libqt5xml5:i386 (5.3.2+dfsg-4+deb8u2)
libsdl2-2.0-0:i386 (2.0.2+dfsg1-6)
libtinyxml2-2:i386 (2.2.0-1)
libva-glx1:i386 (1.4.1-1)
libzen0:i386 (0.4.29-1)
python3-sip (4.16.4+dfsg-1)

Here is the output when I try to start vidcutter on terminal:
```
$ vidcutter
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==4.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 39, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 39, in <module>
    from vidcutter.about import About
  File "/usr/lib/python3/dist-packages/vidcutter/about.py", line 36, in <module>
    import vidcutter.libs.mpv as mpv
ImportError: /usr/lib/python3/dist-packages/vidcutter/libs/mpv.cpython-34m-i386-linux-gnu.so: undefined symbol: mpv_opengl_cb_uninit_gl
```
Do I only miss a package?!? I have already tried to install the packages python-pyqt5.qtopengl (5.3.2+dfsg-3) and python-pyqt5 (5.3.2+dfsg-3) and mpv (0.8.3-dmo1) in addition, but with no luck...
I have already tried the workaround from PandaJim (install python3-pip, run sudo pip3 install --upgrade PyOpenGL), but with the same results (same error message).

Or is my version of python or libmpv (or any other package) just not compatible to vidcutter 4.0?

If not compatible, where can I get older vidcutter 3.x versions (.deb) for download?
I know that I can download the vidcutter 3.5 "src" package here on github, but I need the precompiled .deb package... ;-) Thank You!

**Comment by dodona2** [comment]
go Fedora.

**Comment by manjarooo** [comment]
@dodona2 
What's so funny about this?!? 
If you don't have a helpful answer... please just don't!

**Comment by ozmartian** [comment]
@manjarooo 

from your logs i can see that you're on 32-bit and not 64-bit.. there was a bug in VidCutter preventing the latest version from working on 32-bit machines on Linux only. sorry about that. theh good news is v4.5 is being released in about a week from today which has been fixed and tested thoroughly on 32bit machines so keep an eye out for it...

cheers,
Pete

**Comment by Lin-Buo-Ren** [comment]
Reproduced on KDE neon User Edition 5.11(Based on Ubuntu 16.04), and probably same of issue #73, #86 and #88

**Comment by zellerede** [comment]
It has also a bug report on PyOpenGL, with a workaround solution in the code:
https://sourceforge.net/p/pyopengl/mailman/pyopengl-users/?viewmonth=201702
