### ISSUE TITLE
vidcutter 4.0 not launch

### ISSUE THREAD

**Issue by PandaJim** [ozmartian/vidcutter#73]
Just installed the 4.0 deb from the PPA:

<a href="https://launchpad.net/~ozmartian/+archive/ubuntu/apps">https://launchpad.net/~ozmartian/+archive/ubuntu/apps</a>

**Comment by PandaJim** [comment]
Sorry for the mistake, but I can't edit the comment due to old Chrome version not supported by Github.

Vidcutter 4.0 installed on Ubuntu 16.04 via the deb from PPA, but it does not launch:

Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==4.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 39, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 48, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in <module>
    from OpenGL import GL
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'

**Comment by jeekajoo** [comment]
dup of #72 ;)

**Comment by PandaJim** [comment]
Not know what's the problem, but I got a workaround by upgrade PyOpenGL via following command:

pip3 install --upgrade PyOpenGL

**Comment by sergiozar** [comment]
Hi! really love this software, working until yesterday on linux mint 18.1 cinnamon 64 bit.
I tried the workaround you suggested with this result:

pip3 install --upgrade PyOpenGL
Collecting PyOpenGL
  Using cached PyOpenGL-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oueiew27/PyOpenGL/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


I also tried the suggestion done by the script:

pip install --upgrade PyOpenGL
Collecting PyOpenGL
  Using cached PyOpenGL-3.1.0.tar.gz
Building wheels for collected packages: PyOpenGL
  Running setup.py bdist_wheel for PyOpenGL ... done
  Stored in directory: /home/john/.cache/pip/wheels/1c/17/50/f69d63e0a8169fb890f5a167817a73391be85d30e86fd29504
Successfully built PyOpenGL
Installing collected packages: PyOpenGL
Exception:
Traceback (most recent call last):
  File "/home/john/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/john/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/john/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/john/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/john/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/john/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/john/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/john/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permesso negato: '/usr/local/lib/python2.7/dist-packages/OpenGL'


The strange thing is...I also tried the 3.5 linux 64bit appimage but nothing happens. So...this may be a system update result? 

Thanks in advance for all your work and the help
Sergio

**Comment by armageddon51** [comment]
Ok then, the problem is known. Won't launch either in Mint Cinnamon 18.2. Same errors as PandaJim. Previous version ok (3.5.2 ?)
Thanks

**Comment by sergiozar** [comment]
The 3.5.0 and 3.2.0 appimage won't launch and I really don't have the guts to build from the source. Thanks anyway. I'll patiently wait future versions.
Thanks

**Comment by sergiozar** [comment]
The 3.5.0 and 3.2.0 appimage won't launch and I really don't have the guts to build from the source. Thanks anyway. I'll patiently wait future versions.
Thanks

**Comment by sergiozar** [comment]
OK sorry to bother: appimage 3.0.0 works just fine!!
Thanks!!
