### ISSUE TITLE
Doesn't launch on Ubuntu

### ISSUE THREAD

**Issue by tenleftfingers** [ozmartian/vidcutter#86]
4.0.0 AppImage gives the below error(s) output. I'm running Ubuntu 16.04, fully up-to-date. 64-bit:

```
$ ./VidCutter-4.0.0-x64.AppImage 
/bin/bash: /tmp/.mount_VidCut1zZDTL/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
Traceback (most recent call last):
  File "/tmp/.mount_VidCut1zZDTL/usr/bin/vidcutter", line 16, in <module>
    sys.exit(load_entry_point('vidcutter', 'gui_scripts', 'vidcutter')())
  File "/tmp/.mount_VidCut1zZDTL/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/.mount_VidCut1zZDTL/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2652, in load_entry_point
    return ep.load()
  File "/tmp/.mount_VidCut1zZDTL/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2306, in load
    return self.resolve()
  File "/tmp/.mount_VidCut1zZDTL/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2312, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 39, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 48, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in <module>
    from OpenGL import GL
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 19, in <module>
    from OpenGL.arrays.arraydatatype import *
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/arraydatatype.py", line 14, in <module>
    from OpenGL_accelerate.arraydatatype import ArrayDatatype as ADT
  File "arraydatatype.pyx", line 1, in init OpenGL_accelerate.arraydatatype (src/arraydatatype.c:10964)
  File "wrapper.pyx", line 3, in init OpenGL_accelerate.wrapper (src/wrapper.c:11183)
  File "/usr/lib/python3/dist-packages/OpenGL/error.py", line 224, in <module>
    ErrorChecker = _ErrorChecker( platform )
  File "errorchecker.pyx", line 17, in OpenGL_accelerate.errorchecker._ErrorChecker.__init__ (src/errorchecker.c:818)
TypeError: __init__() takes at least 2 positional arguments (1 given)

```
I tried the PPA executable instead but got another error:
```
$ vidcutter --help
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==4.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 39, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 48, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in <module>
    from OpenGL import GL
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'

```

**Comment by jeekajoo** [comment]
Dup of #72 for ppa. Looks like @ozmartian is not reading the issues..
