### ISSUE TITLE
not working vidcutter ubuntu 16.04

### ISSUE THREAD

**Issue by ramzydoni** [ozmartian/vidcutter#88]
i try install vidcutter new version 4.0 in ubuntu 16.04 not work ؟ 
http://i.imgur.com/53mf0go.png

please fix this probleme :(

**Comment by phd21** [comment]
Hi vidcutter developers,

First, I really like this application, thank you for providing it.

Second, I cannot get v4.x. to even come up in Linux Mint 18.x based on Ubuntu 16.04 either using the PPA, or the AppImage. I am really looking forward to trying the joiner feature as well. Is there a fix, or work around for this? 

Best regards to you and yours,

Phil
phd21

**Comment by FredVoisin** [comment]
Same here on Ubuntu 16.04 amd64 and ppa.
Run in terminal returns the following 

```
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==4.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 39, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 48, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in <module>
    from OpenGL import GL
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'
```

**Comment by davekimble2** [comment]
Exactly the same as Fred here.  Version=4.0.0.201708100203 .  This was working some weeks ago, so think OpenGL might have changed since.

**Comment by JPRuehmann** [comment]
Same for me.
Is there a Way to run vidcutter in kubuntu 16.04?
Thanks,
